### ISSUE TITLE
Only OpenShift cluster supported? Seems that keycloak-operator fails to work in normal k8s cluster

### ISSUE THREAD

**Issue by JiyeYu** [integr8ly/keycloak-operator#100]
In the README.md, there are such sentences:

```
Test it locally
Note: You will need a running Kubernetes or OpenShift cluster to use the Operator
```

It says that normal Kubernetes cluster is also OK to run this operator. However...

## Description
I ran the keycloak-operator on my k8s-cluster. And it failed to create a keycloak pod.
Error messages:
```
time="2019-09-09T01:22:15Z" level=info msg="Keycloak: minexample, Phase: provisionDataLayer"
time="2019-09-09T01:22:15Z" level=error msg="error syncing key (default/minexample): phase provision data layer failed: failed to get runtime objects during provision: the server could not find the requested resource (post processedtemplates.template.openshift.io)"
```

## Expected Behavior
NO ERROR Messages appear and succeeds to create a keycloak pod.

## Actual Behavior
Error messages appear and failed to create a keycloak pod

**Comment by davidffrench** [comment]
Hi @JiyeYu, So sorry for the late reply on this issue. You are absolutely correct, unfortunately, this version of the operator is currently not supported on Kubernetes.

This operator is in the process of refactoring to support among other things, Kubernetes and Keycloak alongside RH-SSO. This new repo is here - https://github.com/keycloak/keycloak-operator/, it looks like you are aware of this as I see you already commented on my PR, thank you for that. It is likely going to be a number of weeks before this is in a functional useable state.

**Comment by JiyeYu** [comment]
I see. Thank you for your comment!

**Comment by KramKroc** [comment]
I don't think this should have been closed as the incorrect information is still present in the README.md document.
