### ISSUE TITLE
Unable to launch keycloack instance

### ISSUE THREAD

**Issue by sunsingerus** [integr8ly/keycloak-operator#101]
## Description

Unable to launch keycloack instance from examples provided

## Expected Behavior

Keycloack instance launched 

## Actual Behavior

when running the following commands;
```bash
kubectl create -f deploy/examples/keycloak.json -n key
kubectl create -f deploy/examples/keycloakRealm.json -n key
```
no keycloack instance is launched.
Got the following error instead;
```console
time="2019-10-13T14:20:47Z" level=error msg="error syncing key (key/example): phase provision data layer failed: failed to get runtime objects during provision: the server could not find the requested resource (post processedtemplates.template.openshift.io)"
```
## Environment
k8s AWS EC2-based instance created with `kops`
latest `master` operator sources from github.

* Operating system: (E.g RHEL 7.6 )
* OpenShift versions:

* Go Version:(E.g go1.10.2)
* Project Version/Tag: (E.g release-1.0.1)

**Comment by KramKroc** [comment]
I wonder if this is related to this issue: https://github.com/integr8ly/keycloak-operator/issues/100

**Comment by davidffrench** [comment]
@KramKroc , you are absolutely correct. I have created a PR to remove Kubernetes references in the Readme - https://github.com/integr8ly/keycloak-operator/pull/104.

This version of the keycloak operator does not work in native Kubernetes. We are refactoring this operator and the new version will work with native Kubernetes. This is still under development but will be fully functional in roughly 2 weeks. https://github.com/keycloak/keycloak-operator/
