### ISSUE TITLE
Add Flag for one time setup rather than constant reconciliation

### ISSUE THREAD

**Issue by maleck13** [integr8ly/keycloak-operator#17]
## Description
During development it is likely that the developer will want to change things about their realm and or their clients etc. 
It would be very frustrating to have those changes keep getting wiped out. To avoid this we should add a flag that indicates to the operator only reconcile this once and then leave it alone.
This flag should default to false

ping @philbrookes

**Comment by philbrookes** [comment]
I like this idea, I would call the flag "createOnly" and I think it should be on a per-CR level, i.e. one client could have "createOnly: true" and not be reconciled, while another client in the same realm and namespace could have "createOnly: false" and be reconciled frequently.

I do think that if a client is created with "createOnly: true" and the created client is subbsequently deleted from the service, that the operator would recreate it. Also, if the client CR is deleted, the client in the service would also be deleted. WDYT?

**Comment by pb82** [comment]
@philbrookes i think this can be closed, `createOnly` has been added since
