### ISSUE TITLE
Operator shouldn't delete users that I've created manually via the SSO Web Console

### ISSUE THREAD

**Issue by david-martin** [integr8ly/keycloak-operator#18]
Currently the operator deletes any users that I've manually created in the 'openshift' realm in an integreatly cluster via the SSO Web Console
.
My use case is I want a user for testing SSO integreation that hasn't been setup ahead of time in the integreatly cluster. I'd like to see how different products, 3scale specifically in this case, behaves when you login if that user wasn't also created ahead of time in 3scale (and linked by having the same email address).
However, as soon as i create this new user in the openshift realm, it gets deleted.

Besides my use case, I would see a valid use case for Integreatly administrators where they want to add additional users manually to the SSO instance after the cluster has been created.

To workaround this I had to scale down the keycloak operator, then create the user. 
I also can't start the operator again.

**Comment by philbrookes** [comment]
@david-martin this definitely needs to be addressed, as it stands right now, I'd expect it to be dealt with as part of this trello: https://trello.com/c/f5NYsFKp/265-break-out-rh-sso-client-as-an-independent-cr as pointed out in the proposal doc here: https://docs.google.com/a/redhat.com/document/d/1eiAyK1x8QjxXH4eIYW8wTtEsL3rDtIGe7veiI5JGp8M/edit?disco=AAAACXcuDgg

**Comment by pb82** [comment]
@david-martin i think this is supported now via the `createOnly`flag. Closing this.
