### ISSUE TITLE
Backup CronJob name is 'daily-at-midnight', when the time is actually 0230hrs

### ISSUE THREAD

**Issue by david-martin** [integr8ly/keycloak-operator#49]
This could cause confusion.
Also, it's not clear from the name what part of sso it backups up (volume or database).

```
sso       daily-at-midnight   30 2 * * *   False     0         <none>    1s
```

I'd suggest a more meaningful name that is decoupled from the time of the backup (as this can vary) e.g. `sso-postgres-backup`

**Comment by davidffrench** [comment]
Thanks @david-martin . It is now possible in the new operator to supply your own Cron schedule to the KeycloakBackup CR. 

Specific docs for the backups are here - https://github.com/keycloak/keycloak-operator/blob/master/docs/backups.asciidoc
