### ISSUE TITLE
make image/build/test fails

### ISSUE THREAD

**Issue by slaskawi** [integr8ly/keycloak-operator#61]
## Description

When I invoke `make image/build/test` I get the following failure:

```
make image/build/test
operator-sdk build --enable-tests docker.io/integreatly/keycloak-operator:v1.3.4
FATA[0000] Must run command in project root dir: project structure requires ./build/Dockerfile 
make: *** [Makefile:59: image/build/test] Error 1
```

## Environment

* Operating system: Fedora F29
* Go Version: `go version go1.10.3 linux/amd64`
* Project Version/Tag: `master`
* Operator SDK version: `operator-sdk version: v0.7.0`

**Comment by philbrookes** [comment]
Hey Sebastian thanks for opening this issue.

Currently the keycloak-operator is built with 0.0.7 of the operator-sdk, although we do want to upgrade it to use the latest 0.6.0, it is currently incompatible.

You will need to install the 0.0.7 version of the operator-sdk to use the commands in the makefile.

**Comment by slaskawi** [comment]
@philbrookes Ok, thanks a lot Phil!
