### ISSUE TITLE
The keycloak operator will cause the keycloak realm CR to be updated infinitely even when there are no changes made to the CR

### ISSUE THREAD

**Issue by wei-lee** [integr8ly/keycloak-operator#66]
## Description

I noticed this behaviour when I try to watch a keycloakrealm CR. The client will keep getting `MODIFIED` event when there is actually no changes made to the CR.

You can see this happening by running:

```
oc get keycloakrealm <name> -w
```

and you will see new messages almost everyone one second to say that the CR is modified, but in fact there are no changes to it at all.

## Expected Behavior

The `modified` event is only generated when there are actually changes made to the CR.

## Actual Behavior

A lot of `modified` event are generated even when there are no changes to the CR.

## Possible solution

I believe the issue is caused by this: https://github.com/integr8ly/keycloak-operator/blob/master/pkg/keycloak/realm/realmHandler.go#L97-L102. When the phase is set to `reconcile`, the logic here will set the phase to the same value over and over again. So to fix it, we should not update the CR again.

ping @philbrookes @pb82

**Comment by grdryn** [comment]
I came here to report a different issue, but I'm just going to lump it in here along with this one. I've just seen a KeycloakRealm with the status phase set to "reconcile" (as in Wei's case above). My issue is that "reconcile" is confusing as a phase to me: is it *reconciling* or *reconciled* or something else?

**Comment by davidffrench** [comment]
Thanks @wei-lee and @grdryn . Both of these issues are now resolved in the new Keycloak Operator - https://github.com/keycloak/keycloak-operator
