### ISSUE TITLE
Add support for minishift

### ISSUE THREAD

**Issue by wei-lee** [integr8ly/keycloak-operator#67]
## Description

It looks like the operator is relying on a rh-sso image stream to be available in OpenShift in order to work. However, I don't think it is available in minishift by default and that has caused an issue that the deployment is never started when I try to use it in minishift, see the attached screenshot:

![Screenshot from 2019-05-28 16-02-27](https://user-images.githubusercontent.com/912729/58630723-337eb700-82d8-11e9-860b-90d0d05989d8.png)

I think it should use the default keycloak template upstream, and only use the rh-sso image stream downstream

**Comment by davidffrench** [comment]
Closing this issue @wei-lee . Please see the new operator which has support for Keycloak. 

https://github.com/keycloak/keycloak-operator
